plugins {
  id 'java-library'
  alias(libs.plugins.kotlin.jvm)
  alias(libs.plugins.kotlin.serialization)
}

apply from: '../buildsystem/maven-push.gradle'
apply from: '../buildsystem/bintray-push.gradle'
apply from: '../buildsystem/sqlite-support.gradle'

dependencies {
  implementation project(':runtime')
  implementation libs.serialization.json
  implementation libs.android.sqlite
  implementation rootProject.ext.androidJar

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.android.sqlite.bundled.jvm
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include '**/*Test.class'
}
