plugins {
  id 'java'
  id 'org.jetbrains.kotlin.kapt'
  alias(libs.plugins.kotlin.jvm)
}

apply from: '../buildsystem/maven-push.gradle'
apply from: '../buildsystem/bintray-push.gradle'

dependencies {
  implementation project(':compiler-core')
  implementation project(':runtime')

  implementation libs.auto.service
  implementation libs.dagger
  implementation libs.java.poet
  implementation libs.kotlin.poet
  implementation libs.kotlin.reflect

  compileOnly libs.incap

  kapt libs.dagger.compiler
  kapt libs.incap.processor
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}
