import com.android.build.api.variant.BuildConfigField

plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.android.legacy.kapt)
  alias(libs.plugins.sqlitemagic)
}

android {
  namespace 'com.siimkinks.sqlitemagic.kotlin'
  compileSdk libs.versions.android.compile.sdk.get().toInteger()
  buildToolsVersion libs.versions.android.build.tools.get()

  defaultConfig {
    applicationId "com.siimkinks.sqlitemagic"
    minSdk libs.versions.android.min.sdk.get().toInteger()
    targetSdk libs.versions.android.target.sdk.get().toInteger()
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_21
    targetCompatibility JavaVersion.VERSION_21
  }
  buildFeatures {
    buildConfig = true
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
  lint {
    abortOnError false
  }
  sourceSets {
    main.kotlin.directories.add('src/main/kotlin')
    debug.kotlin.directories.add('build/generated/source/kaptKotlin/debug')
    test.kotlin.directories.add('src/test/kotlin')
    androidTest.kotlin.directories.add('src/androidTest/kotlin')
  }
}

androidComponents {
  onVariants(selector().all()) { variant ->
    variant.buildConfigFields.put(
        'DB_VERSION',
        new BuildConfigField('int', variant.buildType == 'release' ? '2' : '3', null)
    )
    variant.buildConfigFields.put(
        'DB_NAME',
        new BuildConfigField('String', '"db.db"', null)
    )
  }
}

dependencies {
  implementation libs.android.sqlite.framework
  implementation libs.android.appcompat
  implementation libs.rx.java2
  implementation libs.rx.java2.extensions
  implementation libs.support.time

  kapt libs.sqlitemagic.kotlin

  testImplementation libs.kotlin.reflect
  testImplementation libs.mockito
  testImplementation libs.mockito.kotlin
  testImplementation libs.truth

  androidTestImplementation libs.android.annotations
  androidTestImplementation libs.android.test.runner
  androidTestImplementation(libs.truth) {
    exclude group: 'junit' // Android has JUnit built in.
  }
}

sqlitemagic {
//  generateMagicMethods = false
//	generateLogging = true
//	debugBytecodeProcessor = true
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}
