package com.siimkinks.sqlitemagic

object NameConst {
  const val PACKAGE_ROOT = "com.siimkinks.sqlitemagic"

  const val CLASS_MODEL_DAO = "Dao"
  const val CLASS_MODEL_HANDLER = "Handler"
  const val CLASS_TABLE_STRUCTURE = "Table"
  const val CLASS_INSERT = "InsertBuilder"
  const val CLASS_BULK_INSERT = "BulkInsertBuilder"
  const val CLASS_UPDATE = "UpdateBuilder"
  const val CLASS_BULK_UPDATE = "BulkUpdateBuilder"
  const val CLASS_PERSIST = "PersistBuilder"
  const val CLASS_BULK_PERSIST = "BulkPersistBuilder"
  const val CLASS_DELETE = "DeleteBuilder"
  const val CLASS_BULK_DELETE = "BulkDeleteBuilder"
  const val CLASS_DELETE_TABLE = "DeleteTableBuilder"

  const val METHOD_CREATE = "create"
  const val METHOD_EXECUTE = "execute"
  const val METHOD_OBSERVE = "observe"
  const val METHOD_CONNECTION_PROVIDER = "usingConnection"

  const val FIELD_VIEW_QUERY = "QUERY"
  const val FIELD_INSERT_SQL = "INSERT_SQL"
  const val FIELD_UPDATE_SQL = "UPDATE_SQL"
  const val FIELD_TABLE_SCHEMA = "TABLE_SCHEMA"

  const val METHOD_TO_SQL_ARG = "toSqlArg"
  const val METHOD_GET_FROM_CURSOR = "getFromCursor"
  const val METHOD_GET_FROM_STATEMENT = "getFromStatement"
  const val METHOD_AS = "as"
  const val METHOD_NEW_INSTANCE_WITH_ONLY_ID = "newInstanceWithOnlyId"
  const val METHOD_ADD_SHALLOW_QUERY_PARTS = "addShallowQueryParts"
  const val METHOD_ADD_SHALLOW_QUERY_PARTS_INTERNAL = "addShallowQueryPartsInternal"
  const val METHOD_ADD_DEEP_QUERY_PARTS = "addDeepQueryParts"
  const val METHOD_ADD_DEEP_QUERY_PARTS_INTERNAL = "addDeepQueryPartsInternal"
  const val METHOD_MAPPER = "mapper"
  const val METHOD_FULL_OBJECT_FROM_CURSOR_POSITION = "fullObjectFromCursorPosition"
  const val METHOD_SHALLOW_OBJECT_FROM_CURSOR_POSITION = "shallowObjectFromCursorPosition"
  const val METHOD_SET_ID = "setId"
  const val METHOD_GET_ID = "getId"
  const val METHOD_SET_CONFLICT_ALGORITHM = "conflictAlgorithm"
  const val METHOD_BY_COLUMN = "byColumn"
  const val METHOD_SET_IGNORE_NULL_VALUES = "ignoreNullValues"
  const val METHOD_IS_UNIQUE_COLUMN_NULL = "isUniqueColumnNull"
  const val METHOD_BIND_UNIQUE_COLUMN = "bindUniqueColumn"
  const val METHOD_BIND_TO_UPDATE_STATEMENT = "bindToUpdateStatement"
  const val METHOD_BIND_TO_UPDATE_STATEMENT_WITH_COMPLEX_COLUMNS = "bindToUpdateStatementWithComplexColumns"
  const val METHOD_BIND_TO_INSERT_STATEMENT = "bindToInsertStatement"
  const val METHOD_BIND_TO_NOT_NULL = "bindNotNull"
  const val METHOD_DELETE = "delete"
  const val METHOD_DELETE_TABLE = "deleteTable"
  const val METHOD_GET_INSERT_STATEMENT = "getInsertStatement"
  const val METHOD_INTERNAL_INSERT = "internalInsert"
  const val METHOD_INSERT = "insert"
  const val METHOD_GET_UPDATE_STATEMENT = "getUpdateStatement"
  const val METHOD_UPDATE = "update"
  const val METHOD_INTERNAL_UPDATE = "internalUpdate"
  const val METHOD_PERSIST = "persist"
  const val METHOD_INTERNAL_PERSIST = "internalPersist"
  const val METHOD_INTERNAL_PERSIST_IGNORING_NULL_VALUES = "internalPersistIgnoringNullValues"
  const val METHOD_COLUMN_FOR_VALUE_OR_NULL = "columnForValueOrNull"
  const val METHOD_CALL_INTERNAL_PERSIST_ON_COMPLEX_COLUMNS = "callInternalPersistsOnComplexColumns"
  const val METHOD_CALL_INTERNAL_PERSIST_IGNORING_NULL_VALUES_ON_COMPLEX_COLUMNS = "callInternalPersistsIgnoringNullValuesOnComplexColumns"
  const val METHOD_CALL_INTERNAL_INSERT_ON_COMPLEX_COLUMNS = "callInternalInsertsOnComplexColumns"
  const val METHOD_CALL_INTERNAL_UPDATE_ON_COMPLEX_COLUMNS = "callInternalUpdatesOnComplexColumns"
}
