plugins {
  id 'java'
  alias(libs.plugins.kotlin.jvm)
}

apply from: '../buildsystem/maven-push.gradle'
apply from: '../buildsystem/bintray-push.gradle'


dependencies {
  implementation project(':annotations')

  implementation fileTree(dir: 'libs', include: ['*.jar'])

  implementation rootProject.ext.androidJar
  implementation libs.android.annotations
  implementation libs.android.sqlite
  implementation libs.rx.java2

  testImplementation libs.junit
  testImplementation libs.truth
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}
