package com.siimkinks.sqlitemagic

import com.siimkinks.sqlitemagic.transformer.BooleanTransformer

object Const {
  const val GENERATION_COMMENT = "Generated by SqliteMagic. Do not modify!"

  val DEFAULT_TRANSFORMERS = listOf(
    BooleanTransformer::class.qualifiedName!!
  )

  val SUPPORTED_TRANSFORMER_DESERIALIZED_TYPES = listOf(
    Long::class.simpleName,
    Int::class.simpleName,
    Short::class.simpleName,
    Double::class.simpleName,
    Float::class.simpleName,
    ByteArray::class.simpleName,
    Byte::class.simpleName,
    String::class.simpleName
  )
}
