package com.siimkinks.sqlitemagic

internal object GeneratedNames {
  const val PACKAGE_ROOT = "com.siimkinks.sqlitemagic"

  const val CLASS_NAME_MAIN_GENERATED_CLASSES_MANAGER = "SqliteMagicDatabase"
  const val CLASS_NAME_GENERATED_CLASSES_MANAGER = "GeneratedClassesManager"
  const val CLASS_MODEL_DAO = "Dao"
  const val CLASS_TABLE_STRUCTURE = "Table"

  const val PROPERTY_DB_VERSION = "dbVersion"
  const val PROPERTY_DB_NAME = "dbName"
  const val PROPERTY_SUBMODULE_NAMES = "submoduleNames"
  const val PROPERTY_IS_DEBUG = "isDebug"

  const val FIELD_VIEW_QUERY = "QUERY"
  const val FIELD_GENERATED_VIEW = "GENERATED_VIEW"
  const val FIELD_TABLE_SCHEMA = "TABLE_SCHEMA"
  const val FIELD_TRIGGER_TABLE_NAMES = "triggerTableNames"
  const val FIELD_MODULE_NAME = "moduleName"
  const val FIELD_TABLE_NAME = "tableName"
  const val FIELD_INSERT_SQL = "insertSql"
  const val FIELD_TABLE_POSITION = "tablePosition"
  const val FIELD_WITHOUT_ROW_ID = "withoutRowId"
  const val FIELD_MAX_COLUMNS = "maxColumns"
  const val FIELD_DEFAULT_IDENTITY_COLUMN = "defaultIdentityColumn"

  const val VARIABLE_VALUE = "value"
  const val VARIABLE_SQL_VALUE = "sqlValue"
  const val VARIABLE_DB_VALUE = "dbValue"
  const val VARIABLE_ALIAS = "alias"
  const val VARIABLE_GENERATED_RELATIONSHIP_IDS = "generatedRelationshipIds"
  const val VARIABLE_OPERATIONS = "operations"

  const val METHOD_AS = "as"
  const val METHOD_NEW_INSTANCE_WITH_ONLY_ID = "newInstanceWithOnlyId"
  const val METHOD_ADD_SHALLOW_QUERY_PARTS = "addShallowQueryParts"
  const val METHOD_ADD_DEEP_QUERY_PARTS = "addDeepQueryParts"
  const val METHOD_MAPPER = "mapper"
  const val METHOD_CREATE_MAPPER = "createMapper"
  const val METHOD_FULL_OBJECT_FROM_CURSOR_POSITION = "fullObjectFromCursorPosition"
  const val METHOD_SHALLOW_OBJECT_FROM_CURSOR_POSITION = "shallowObjectFromCursorPosition"
  const val METHOD_BY_COLUMN = "byColumn"
  const val METHOD_BIND_TO_UPDATE_STATEMENT = "bindToUpdateStatement"
  const val METHOD_BIND_TO_INSERT_STATEMENT = "bindToInsertStatement"
  const val METHOD_BIND_NOT_NULL_FOR_INSERT = "bindNotNullForInsert"
  const val METHOD_BIND_NOT_NULL_FOR_UPDATE = "bindNotNullForUpdate"
  const val METHOD_IDENTITY = "identity"
  const val METHOD_HAS_IDENTITY_VALUE = "hasIdentityValue"
  const val METHOD_UPDATE_STATEMENT_SQL = "updateStatementSql"
  const val METHOD_ASSIGN_GENERATED_ID = "assignGeneratedId"
  const val METHOD_INSERT_RELATIONSHIPS = "insertRelationships"
  const val METHOD_UPDATE_RELATIONSHIPS = "updateRelationships"
  const val METHOD_PERSIST_RELATIONSHIPS = "persistRelationships"
  const val METHOD_REMEMBER_GENERATED_ID = "rememberGeneratedId"
  const val METHOD_DELETE = "delete"
  const val METHOD_DELETE_TABLE = "deleteTable"
  const val METHOD_INSERT = "insert"
  const val METHOD_UPDATE = "update"
  const val METHOD_PERSIST = "persist"
  const val METHOD_CREATE_SCHEMA = "createSchema"
  const val METHOD_CREATE_TEMPORARY_SCHEMA = "createTemporarySchema"
  const val METHOD_CLEAR_DATA = "clearData"
  const val METHOD_MIGRATE_VIEWS = "migrateViews"
  const val METHOD_CONFIGURE_DATABASE = "configureDatabase"
  const val METHOD_GET_NR_OF_TABLES = "getNrOfTables"
  const val METHOD_COLUMN_FOR_VALUE = "columnForValue"
  const val METHOD_COLUMN_FOR_VALUE_OR_NULL = "columnForValueOrNull"
  const val METHOD_CREATE_SCHEMA_TABLES = "createSchemaTables"
  const val METHOD_COLLECT_GENERATED_VIEWS = "collectGeneratedViews"
  const val METHOD_CREATE_SCHEMA_INDEXES = "createSchemaIndexes"
}
