package com.siimkinks.sqlitemagic.transformer

import com.google.common.truth.Truth.assertThat
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.siimkinks.sqlitemagic.Environment
import com.siimkinks.sqlitemagic.dbconfig.DatabaseConfigurationCollectionStep
import com.siimkinks.sqlitemagic.processing.ProcessingStep
import com.siimkinks.sqlitemagic.processing.ProcessingStepResult
import com.siimkinks.sqlitemagic.processing.ProcessingStepResult.Continue
import com.siimkinks.sqlitemagic.transformer.TransformerCollectionSources.FIXTURE_PACKAGE
import com.siimkinks.sqlitemagic.transformer.TransformerCollectionSources.emailValueType
import com.siimkinks.sqlitemagic.transformer.TransformerCollectionSources.javaTransformerSource
import com.siimkinks.sqlitemagic.transformer.TransformerCollectionSources.kotlinTransformerSource
import com.siimkinks.sqlitemagic.transformer.TransformerCollectionSources.nullableObjectTransformer
import com.siimkinks.sqlitemagic.transformer.TransformerCollectionSources.objectTransformer
import com.siimkinks.sqlitemagic.utils.ProcessingStepsTest
import com.siimkinks.sqlitemagic.utils.SqliteMagicCompilation
import com.siimkinks.sqlitemagic.utils.assertContains
import com.siimkinks.sqlitemagic.utils.assertDoesNotContain
import com.tschuchort.compiletesting.SourceFile
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

internal class TransformerCodeGenerationStepTest : ProcessingStepsTest {
  override val processingSteps
    get() = { env: Environment ->
      listOf(
        DefaultTransformerCollectionStep(env),
        DatabaseConfigurationCollectionStep(env),
        TransformerCollectionStep(env),
        TransformerCodeGenerationStep(env)
      )
    }

  @Nested
  inner class ColumnTypesAndNullability {
    @Test
    fun `generates transformer column`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          objectTransformer()
        )
        .isOk()
        .assertGeneratedSource(
          fileName = "EmailColumn.kt",
          expectedSource = """
            // Generated by SqliteMagic. Do not modify!
            package com.siimkinks.sqlitemagic

            import android.database.Cursor
            import androidx.sqlite.db.SupportSQLiteStatement
            import $FIXTURE_PACKAGE.Email
            import $FIXTURE_PACKAGE.EmailTransformer
            import kotlin.Boolean
            import kotlin.String
            import kotlin.Suppress

            public class EmailColumn<T, N> internal constructor(
              table: Table<T>,
              name: String,
              valueParser: Utils.ValueParser<*>,
              nullable: Boolean,
              alias: String?,
            ) : Column<Email, Email, Email, T, N>(table, name, false, valueParser, nullable, alias) {
              override fun toSqlArg(`value`: Email): String = EmailTransformer.emailToString(`value`)

              override fun `as`(alias: String): EmailColumn<T, N> = EmailColumn<T, N>(table, name, valueParser, nullable, alias)

              @Suppress("UNCHECKED_CAST")
              override fun <V> getFromCursor(cursor: Cursor): V? {
                val dbValue = super.getFromCursor<String>(cursor) ?: return null
                return EmailTransformer.stringToEmail(dbValue) as V?
              }

              @Suppress("UNCHECKED_CAST")
              override fun <V> getFromStatement(statement: SupportSQLiteStatement): V? {
                val dbValue = super.getFromStatement<String>(statement) ?: return null
                return EmailTransformer.stringToEmail(dbValue) as V?
              }
            }
            """.trimIndent() + "\n"
        )
    }

    @Test
    fun `guards nullable serializer results and forwards null values to deserializer`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          nullableObjectTransformer()
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          // Column type
          generatedSource.assertContains(
            ") : Column<Email, Email, Email, T, N>(table, name, false, valueParser, nullable, alias) {"
          )

          // Serialization
          generatedSource.assertContains(
            "override fun toSqlArg(`value`: Email): String {",
            "val sqlValue = NullableEmailTransformer.emailToString(`value`)",
            "throw NullPointerException(\"SQL argument cannot be null\")"
          )

          // Deserialization
          generatedSource.assertContains(
            "val dbValue = super.getFromCursor<String>(cursor)",
            "val dbValue = super.getFromStatement<String>(statement)",
            "return NullableEmailTransformer.stringToEmail(dbValue) as V?"
          )
          generatedSource.assertDoesNotContain(
            "super.getFromCursor<String>(cursor) ?: return null",
            "super.getFromStatement<String>(statement) ?: return null"
          )
        }
    }

    @Test
    fun `forwards null database values to nullable Kotlin deserializer`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "NullableSerializedValueTransformer",
            contents = """
              object NullableSerializedValueTransformer {
                @ObjectToDbValue
                fun emailToString(email: Email): String? = email.value

                @DbValueToObject
                fun stringToEmail(value: String?): Email = Email(value.orEmpty())
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "val dbValue = super.getFromCursor<String>(cursor)",
            "val dbValue = super.getFromStatement<String>(statement)",
            "return NullableSerializedValueTransformer.stringToEmail(dbValue) as V?"
          )
          generatedSource.assertDoesNotContain(
            "super.getFromCursor<String>(cursor) ?: return null",
            "super.getFromStatement<String>(statement) ?: return null"
          )
        }
    }

    @Test
    fun `removes only root nullability from parameterized column types`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "NullableEmailListTransformer",
            contents = """
              object NullableEmailListTransformer {
                @ObjectToDbValue
                fun emailsToString(emails: List<Email?>?): String? = emails?.size?.toString()

                @DbValueToObject
                fun stringToEmails(value: String?): List<Email?>? = when (value) {
                  null -> null
                  else -> emptyList()
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("List_EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            ": Column<List<Email?>, List<Email?>, List<Email?>, T, N>"
          )
          generatedSource.assertDoesNotContain(
            ": Column<List<Email?>?, List<Email?>?, List<Email?>?, T, N>"
          )
        }
    }

    @Test
    fun `generates numeric column for numeric serialized type`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "NumericEmailTransformer",
            contents = """
              object NumericEmailTransformer {
                @ObjectToDbValue
                fun emailToLong(email: Email): Long = email.value.length.toLong()

                @DbValueToObject
                fun longToEmail(value: Long): Email = Email(value.toString())
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            ") : NumericColumn<Email, Email, Email, T, N>(table, name, false, valueParser, nullable, alias) {",
            "val dbValue = super.getFromCursor<Long>(cursor) ?: return null",
            "return NumericEmailTransformer.longToEmail(dbValue) as V?"
          )
        }
    }

    @Test
    fun `generates numeric column for nullable numeric serialized type`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "NullableNumericEmailTransformer",
            contents = """
              object NullableNumericEmailTransformer {
                @ObjectToDbValue
                fun emailToLong(email: Email): Long? = email.value.length.toLong()

                @DbValueToObject
                fun longToEmail(value: Long?): Email = Email((value ?: 0L).toString())
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          // Column type
          generatedSource.assertContains(
            ") : NumericColumn<Email, Email, Email, T, N>"
          )

          // Serialization
          generatedSource.assertContains(
            "val sqlValue = NullableNumericEmailTransformer.emailToLong(`value`)",
            "throw NullPointerException(\"SQL argument cannot be null\")"
          )

          // Deserialization
          generatedSource.assertContains(
            "val dbValue = super.getFromCursor<Long>(cursor)",
            "return NullableNumericEmailTransformer.longToEmail(dbValue) as V?"
          )
          generatedSource.assertDoesNotContain(
            "super.getFromCursor<Long>(cursor) ?: return null"
          )
        }
    }

    @Test
    fun `generates column for byte array serialized type`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "ByteArrayEmailTransformer",
            contents = """
              object ByteArrayEmailTransformer {
                @ObjectToDbValue
                fun emailToBytes(email: Email): ByteArray = email.value.encodeToByteArray()

                @DbValueToObject
                fun bytesToEmail(value: ByteArray): Email = Email(value.decodeToString())
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            ") : Column<Email, Email, Email, T, N>",
            "override fun toSqlArg(`value`: Email): String = ByteArrayEmailTransformer.emailToBytes(`value`).toString()",
            "val dbValue = super.getFromCursor<ByteArray>(cursor) ?: return null",
            "return ByteArrayEmailTransformer.bytesToEmail(dbValue) as V?"
          )
        }
    }
  }

  @Nested
  inner class KotlinTransformerReferences {
    @Test
    fun `generates calls to top-level transformer functions`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "EmailTransformer",
            contents = """
              @ObjectToDbValue
              fun emailToString(email: Email): String = email.value

              @DbValueToObject
              fun stringToEmail(value: String): Email = Email(value)
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "override fun toSqlArg(`value`: Email): String = emailToString(`value`)",
            "val dbValue = super.getFromCursor<String>(cursor) ?: return null",
            "return stringToEmail(dbValue) as V?"
          )
        }
    }

    @Test
    fun `generates calls to companion object transformer functions`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "EmailTransformer",
            contents = """
              class EmailTransformer {
                companion object {
                  @ObjectToDbValue
                  fun emailToString(email: Email): String = email.value

                  @DbValueToObject
                  fun stringToEmail(value: String): Email = Email(value)
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "EmailTransformer.Companion.emailToString(`value`)",
            "val dbValue = super.getFromCursor<String>(cursor) ?: return null",
            "EmailTransformer.Companion.stringToEmail(dbValue)"
          )
        }
    }

    @Test
    fun `generates calls to transformer functions in nested object`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "NestedEmailTransformer",
            contents = """
              object TransformerContainer {
                object NestedEmailTransformer {
                  @ObjectToDbValue
                  fun emailToString(email: Email): String = email.value

                  @DbValueToObject
                  fun stringToEmail(value: String): Email = Email(value)
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "TransformerContainer.NestedEmailTransformer.emailToString(`value`)",
            "TransformerContainer.NestedEmailTransformer.stringToEmail(dbValue)"
          )
        }
    }

    @Test
    fun `escapes keyword transformer function names`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "KeywordEmailTransformer",
            contents = """
              object KeywordEmailTransformer {
                @ObjectToDbValue
                fun `when`(email: Email): String = email.value

                @DbValueToObject
                fun `when`(value: String): Email = Email(value)
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "KeywordEmailTransformer.`when`(`value`)",
            "KeywordEmailTransformer.`when`(dbValue)"
          )
        }
    }

    @Test
    fun `resolves colliding top-level transformer function names from different packages`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          SourceFile.kotlin(
            name = "EmailSerializer.kt",
            contents = """
              package $FIXTURE_PACKAGE.serializer

              import com.siimkinks.sqlitemagic.annotation.transformer.ObjectToDbValue
              import $FIXTURE_PACKAGE.Email

              @ObjectToDbValue
              fun transform(email: Email): String = email.value
              """.trimIndent()
          ),
          SourceFile.kotlin(
            name = "EmailDeserializer.kt",
            contents = """
              package $FIXTURE_PACKAGE.deserializer

              import com.siimkinks.sqlitemagic.annotation.transformer.DbValueToObject
              import $FIXTURE_PACKAGE.Email

              @DbValueToObject
              fun transform(value: String): Email = Email(value)
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "$FIXTURE_PACKAGE.serializer.transform",
            "$FIXTURE_PACKAGE.deserializer.transform"
          )
        }
    }
  }

  @Nested
  inner class JavaTransformers {
    @Test
    fun `does not invoke Java non-null deserializer for null database values`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          javaTransformerSource(
            name = "NonNullJavaEmailTransformer",
            contents = """
              import androidx.annotation.NonNull;

              public final class NonNullJavaEmailTransformer {
                @NonNull
                @ObjectToDbValue
                public static String emailToString(@NonNull Email email) {
                  return email.getValue();
                }

                @NonNull
                @DbValueToObject
                public static Email stringToEmail(@NonNull String value) {
                  return new Email(value);
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "val dbValue = super.getFromCursor<String>(cursor) ?: return null",
            "return NonNullJavaEmailTransformer.stringToEmail(dbValue) as V?",
            "val dbValue = super.getFromStatement<String>(statement) ?: return null"
          )
        }
    }

    @Test
    fun `forwards null database values to Java nullable deserializer`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          javaTransformerSource(
            name = "NullableJavaEmailTransformer",
            contents = """
              import androidx.annotation.NonNull;
              import androidx.annotation.Nullable;

              public final class NullableJavaEmailTransformer {
                @Nullable
                @ObjectToDbValue
                public static String emailToString(@NonNull Email email) {
                  return email.getValue();
                }

                @NonNull
                @DbValueToObject
                public static Email stringToEmail(@Nullable String value) {
                  return new Email(value == null ? "" : value);
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            "val dbValue = super.getFromCursor<String>(cursor)",
            "return NullableJavaEmailTransformer.stringToEmail(dbValue) as V?",
            "val dbValue = super.getFromStatement<String>(statement)"
          )
          generatedSource.assertDoesNotContain(
            "super.getFromCursor<String>(cursor) ?: return null",
            "super.getFromStatement<String>(statement) ?: return null"
          )
        }
    }

    @Test
    fun `generates transformer calls for Java primitive serialized type`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          javaTransformerSource(
            name = "PrimitiveJavaEmailTransformer",
            contents = """
              public final class PrimitiveJavaEmailTransformer {
                @ObjectToDbValue
                public static long emailToLong(Email email) {
                  return email.getValue().length();
                }

                @DbValueToObject
                public static Email longToEmail(long value) {
                  return new Email(Long.toString(value));
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            ") : NumericColumn<Email, Email, Email, T, N>",
            "override fun toSqlArg(`value`: Email): String = PrimitiveJavaEmailTransformer.emailToLong(`value`).toString()",
            "val dbValue = super.getFromCursor<Long>(cursor) ?: return null",
            "return PrimitiveJavaEmailTransformer.longToEmail(dbValue) as V?"
          )
        }
    }

    @Test
    fun `guards platform-null Java serializer results`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          javaTransformerSource(
            name = "JavaEmailTransformer",
            contents = """
              public final class JavaEmailTransformer {
                @ObjectToDbValue
                public static String emailToString(Email email) {
                  return email.getValue();
                }

                @DbValueToObject
                public static Email stringToEmail(String value) {
                  return new Email(value);
                }
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("EmailColumn.kt") { generatedSource ->
          // Serialization
          generatedSource.assertContains(
            "val sqlValue = JavaEmailTransformer.emailToString(`value`)",
            "throw NullPointerException(\"SQL argument cannot be null\")"
          )

          // Deserialization
          generatedSource.assertContains(
            "return JavaEmailTransformer.stringToEmail(dbValue) as V?"
          )
        }
    }
  }

  @Nested
  inner class ParameterizedTypes {
    @Test
    fun `generates columns for parameterized transformed types`() {
      SqliteMagicCompilation
        .compile(
          emailValueType(),
          kotlinTransformerSource(
            name = "EmailListTransformer",
            contents = """
              object EmailListTransformer {
                @ObjectToDbValue
                fun emailsToString(emails: List<Email>): String = emails.joinToString(transform = Email::value)

                @DbValueToObject
                fun stringToEmails(value: String): List<Email> = value.split(',').map(::Email)
              }
              """.trimIndent()
          )
        )
        .isOk()
        .withGeneratedSource("List_EmailColumn.kt") { generatedSource ->
          generatedSource.assertContains(
            ": Column<List<Email>, List<Email>, List<Email>, T, N>"
          )
        }
    }
  }

  @Nested
  inner class ProcessingLifecycle {
    @Test
    fun `does not generate columns for default transformers`() {
      assertThat(
        SqliteMagicCompilation
          .compile(emailValueType())
          .isOk()
          .generatedSourceNames()
      ).isEmpty()
    }

    @Test
    fun `generates columns for transformers discovered in a later round`() {
      val result = SqliteMagicCompilation
        .compile(
          emailValueType(),
          processingStepsFactory = { env ->
            listOf(
              DefaultTransformerCollectionStep(env),
              TransformerCollectionStep(env),
              TransformerCodeGenerationStep(env),
              GeneratingTransformerStep(env)
            )
          }
        )
        .isOk()

      assertThat(result.generatedSourceNames()).contains("EmailColumn.kt")
    }
  }

  private class GeneratingTransformerStep(
    private val environment: Environment
  ) : ProcessingStep {
    private var isGenerated = false

    override fun process(resolver: Resolver): ProcessingStepResult = when {
      isGenerated -> Continue
      else -> {
        val emailSource = resolver
          .getAllFiles()
          .first { it.fileName == "Email.kt" }
        environment.codeGenerator
          .createNewFile(
            dependencies = Dependencies(false, emailSource),
            packageName = FIXTURE_PACKAGE,
            fileName = "GeneratedEmailTransformer"
          )
          .bufferedWriter()
          .use { output ->
            output.write(
              """
              package $FIXTURE_PACKAGE

              import com.siimkinks.sqlitemagic.annotation.transformer.DbValueToObject
              import com.siimkinks.sqlitemagic.annotation.transformer.ObjectToDbValue

              object GeneratedEmailTransformer {
                @ObjectToDbValue
                fun emailToString(email: Email): String = email.value

                @DbValueToObject
                fun stringToEmail(value: String): Email = Email(value)
              }
              """.trimIndent()
            )
          }
        isGenerated = true
        Continue
      }
    }
  }
}
