plugins {
  id 'java'
  alias(libs.plugins.kotlin.jvm)
}

apply from: '../buildsystem/maven-push.gradle'
apply from: '../buildsystem/bintray-push.gradle'


dependencies {
  implementation project(':legacy-annotations')
  implementation project(':runtime')

  implementation libs.android.sqlite
  implementation libs.auto.common
  implementation libs.dagger
  implementation libs.guava
  implementation libs.java.poet
  implementation libs.jackson
  implementation libs.rx.java2

  compileOnly libs.dagger.compiler
  compileOnly libs.lombok.new

  annotationProcessor libs.dagger.compiler
  annotationProcessor libs.lombok.new

  testImplementation libs.compile.testing
  testImplementation libs.junit
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}

def setupTestsEnv = tasks.register('setupTestsEnv') {
  doFirst {
    System.setProperty('SQLITE_MAGIC_AUTO_LIB', 'com.google.auto.value.AutoValue')
  }
}

tasks.named('test') {
  dependsOn(setupTestsEnv)
}
