apply plugin: 'maven-publish'

java {
  withSourcesJar()
  withJavadocJar()
}

def publicationName = plugins.hasPlugin('java-gradle-plugin') ? 'pluginMaven' : 'mavenJava'

publishing {
  publications {
    if (publicationName == 'mavenJava') {
      mavenJava(MavenPublication) {
        from components.java
      }
    }

    withType(MavenPublication).configureEach { publication ->
      if (publication.name == publicationName) {
        publication.artifactId = POM_ARTIFACT_ID
        publication.pom { pom ->
          pom.name = POM_NAME
          pom.description = POM_DESCRIPTION
          pom.url = POM_URL
          pom.scm { scm ->
            scm.url = POM_SCM_URL
            scm.connection = POM_SCM_CONNECTION
            scm.developerConnection = POM_SCM_DEV_CONNECTION
          }
          pom.licenses { licenses ->
            licenses.license { license ->
              license.name = POM_LICENCE_NAME
              license.url = POM_LICENCE_URL
              license.distribution = POM_LICENCE_DIST
            }
          }
          pom.developers { developers ->
            developers.developer { developer ->
              developer.id = POM_DEVELOPER_ID
              developer.name = POM_DEVELOPER_NAME
            }
          }
        }
      }
    }
  }
}
