plugins {
  id 'java'
}

apply from: '../buildsystem/maven-push.gradle'
apply from: '../buildsystem/bintray-push.gradle'


dependencies {
  implementation project(':compiler-core')

  implementation libs.auto.service

  compileOnly libs.dagger.compiler
  compileOnly libs.incap

  annotationProcessor libs.auto.service
  annotationProcessor libs.dagger.compiler
  annotationProcessor libs.incap.processor
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}
