plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.android.legacy.kapt)
  alias(libs.plugins.sqlitemagic)
}

android {
  namespace 'com.siimkinks.sqlitemagic.multimodule'
  compileSdk libs.versions.android.compile.sdk.get().toInteger()
  buildToolsVersion libs.versions.android.build.tools.get()

  defaultConfig {
    applicationId "com.siimkinks.sqlitemagic.multimodule"
    minSdk libs.versions.android.min.sdk.get().toInteger()
    targetSdk libs.versions.android.target.sdk.get().toInteger()
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_21
    targetCompatibility JavaVersion.VERSION_21
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }

  flavorDimensions "mode"
  productFlavors {
    demo {
      dimension "mode"
    }
    trial {
      dimension "mode"
    }
    full {
      dimension "mode"
    }
  }

  lint {
    abortOnError false
  }
  sourceSets {
    main.kotlin.directories.add('src/main/java')
    debug.kotlin.directories.add('build/generated/source/kaptKotlin/debug')
    test.kotlin.directories.add('src/test/java')
    androidTest.kotlin.directories.add('src/androidTest/java')
  }
}

dependencies {
  implementation project(':submodule')
  implementation project(':another-submodule')

  implementation libs.android.sqlite.framework
  implementation libs.android.appcompat
  implementation libs.rx.java2

  kapt libs.sqlitemagic.kotlin

  testImplementation libs.kotlin.junit
  testImplementation libs.kotlin.reflect
  testImplementation libs.mockito
  testImplementation libs.mockito.kotlin
  testImplementation libs.truth

  androidTestImplementation libs.android.annotations
  androidTestImplementation libs.android.test.runner
  androidTestImplementation libs.junit.runner
  androidTestImplementation(libs.truth) {
    exclude group: 'junit' // Android has JUnit built in.
  }
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}
