plugins {
  id 'java'
}

apply from: '../buildsystem/maven-push.gradle'
apply from: '../buildsystem/bintray-push.gradle'


dependencies {
  implementation project(':annotations')
  implementation project(':runtime')
  implementation project(':compiler-core')

  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation libs.auto.service
  implementation libs.lombok

  compileOnly libs.dagger.compiler
  compileOnly libs.incap

  annotationProcessor fileTree(dir: 'libs', include: ['*.jar'])
  annotationProcessor libs.auto.service
  annotationProcessor libs.dagger.compiler
  annotationProcessor libs.incap.processor
  annotationProcessor libs.lombok
}

tasks.withType(Test).configureEach {
  scanForTestClasses = false
  include "**/*Test.class"
}
