package com.siimkinks.sqlitemagic.entity

import com.siimkinks.sqlitemagic.exception.OperationFailedException

/**
 * Outcome of persisting a single entity.
 *
 * A persist operation first attempts to update an existing row. If no row is updated, it inserts a new one.
 * The concrete result indicates whether a row was inserted, updated, or left unchanged because the configured
 * conflict algorithm ignored a conflict.
 *
 * Entity IDs are not included in the result because they may be absent or use a type other than
 * SQLite's row ID. The [Inserted] result exposes SQLite's generated row ID when the table has one.
 *
 * Failures not ignored by the configured conflict algorithm are reported with [OperationFailedException].
 */
sealed interface EntityPersistResult {
  /**
   * A new row was inserted.
   *
   * For a rowId table, [rowId] returns the row ID generated by SQLite. This value identifies the
   * SQLite row and may differ from the entity's declared ID. For a `WITHOUT ROWID` table, [rowId] returns `null`.
   *
   * @param rowId row ID generated by SQLite, or `null` when the table has no row ID
   */
  data class Inserted(val rowId: Long?) : EntityPersistResult

  /**
   * An existing row was updated.
   *
   * The result carries no additional value. Any declared entity ID remains available from the entity itself.
   */
  object Updated : EntityPersistResult

  /**
   * No row was inserted or updated because the configured conflict algorithm ignored a conflict.
   *
   * Failures not covered by the conflict algorithm are reported with
   * [OperationFailedException] instead.
   */
  object Ignored : EntityPersistResult
}
