package com.siimkinks.sqlitemagic.entity;

import androidx.annotation.Nullable;

import com.siimkinks.sqlitemagic.exception.OperationFailedException;

/**
 * Outcome of persisting a single entity.
 * <p>
 * A persist operation first attempts to update an existing row. If no row is updated, it inserts
 * a new one. The concrete result indicates whether a row was inserted, updated, or left unchanged
 * because the configured conflict algorithm ignored a conflict.
 * <p>
 * Entity IDs are not included in the result because they may be absent or use a type other than
 * SQLite's row ID. Callers can read a declared entity ID from the entity itself. The
 * {@link Inserted} result exposes SQLite's generated row ID when the table has one.
 * <p>
 * Failures not ignored by the configured conflict algorithm are reported with
 * {@link OperationFailedException}.
 */
public sealed interface EntityPersistResult
    permits EntityPersistResult.Inserted,
    EntityPersistResult.Updated,
    EntityPersistResult.Ignored {

  /**
   * A new row was inserted.
   * <p>
   * For a rowId table, {@link #rowId()} returns the row ID generated by SQLite. This value identifies
   * the SQLite row and may differ from the entity's declared ID. For a {@code WITHOUT ROWID} table,
   * {@link #rowId()} returns {@code null}.
   *
   * @param rowId row ID generated by SQLite, or {@code null} when the table has no row ID
   */
  record Inserted(@Nullable Long rowId) implements EntityPersistResult {
  }

  /**
   * An existing row was updated.
   * <p>
   * The result carries no additional value. Any declared entity ID remains available from the
   * entity itself.
   */
  record Updated() implements EntityPersistResult {
  }

  /**
   * No row was inserted or updated because the configured conflict algorithm ignored a conflict.
   * <p>
   * Failures not covered by the conflict algorithm are reported with
   * {@link OperationFailedException} instead.
   */
  record Ignored() implements EntityPersistResult {
  }
}
